# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: google/cloud-sdk:latest
    environment:
      GOPATH: $HOME/.go_project
      PATH: $PATH:$HOME/.go_workspace/bin
    working_directory: /go/src/github.com/benbromhead/cassandra-operator
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: apt-get -y install golang docker
      - run:
          name: Install Glide
          command: curl https://glide.sh/get | sh
      - restore_cache:
          keys:
              - glide-cache-{{ checksum "glide.lock" }}
      - run:
          name: Install dependencies if not cached
          command: |
              if [ -d ./vendor ]; then
                  echo "vendor directory found"
              else
                  echo "vendor directory not found"
                  sudo apt-get install -y curl
                  curl https://glide.sh/get | sh
                  glide install
              fi
      - save_cache:
          key: glide-cache-{{ checksum "glide.lock" }}
          paths:
              - vendor
        # specify any bash command here prefixed with `run: `
      - run: go test -v ./test/e2e/ --kubeconfig "$HOME/.kube/config" --operator-image="$IMAGE"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build